version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${DB_LINK}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_LINK}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
